# Tomcat server configuration
server:
    port: 8080
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

# actuator/info configuration
info:
    version: "@project.version@"

# Spring configuration
spring:
    flyway:
        schemas: tyxr
        baseline-on-migrate: true
        validate-on-migrate: false
    profiles:
        include: production,security-oauth2
    messages:
        basename: i18n/messages
    datasource:
        url: jdbc:postgresql://localhost:5432/tyxr_dev?currentSchema=tyxr
        username: postgres
        password: P@ssw0rd
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-test-query: SELECT 1
            connection-timeout: 30000 # 30 sec
            idle-timeout: 10000 # 10 sec
            maximum-pool-size: 100 # max 100
            minimum-idle: 5
    jpa:
        properties:
            hibernate:
                default_schema: tyxr
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                show_sql: true
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true # to solve https://github.com/spring-projects/spring-boot/issues/12007
        open-in-view: false

# backend-services specific configuration
backend:
    bcproxy:
        basepath: http://localhost:8081

# logging
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{tmx-correlation-id}] %-5level %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{tmx-correlation-id}] %-5level %logger{36} - %msg%n"
    file: ${java.io.tmpdir}/backend-services.log
    level:
        org.springframework.cloud.config: INFO
        org.springframework.security: INFO
        io.tyxr: DEBUG
